import { UserInfo } from "./types";

export const MOCK_USERS: UserInfo[] = [
  {
    id: "#123456",
    firstName: "Stephen",
    lastName: "Zubairu",
    department: "Technical Team",
    role: "Admin",
    email: "opuenezighan@email.com",
    phoneNumber: "9900123123",
    address: "3 Ebinpejo Lane",
    city: "Idumota",
    state: "Lagos",
    country: "Nigeria",
    postalCode: "101012",
    zone: "Global_Zone",
    location: "Lekki",
  },
  {
    id: "#123457",
    firstName: "Samuel",
    lastName: "Olaniyan",
    department: "Operations",
    role: "Manager",
    email: "samuel.o@email.com",
    phoneNumber: "08012345678",
    address: "12 Marina Street",
    city: "Lagos Island",
    state: "Lagos",
    country: "Nigeria",
    postalCode: "101001",
    zone: "Lagos_Zone",
    location: "Ikeja",
  },
  {
    id: "#123458",
    firstName: "Paul",
    lastName: "Dokubo",
    department: "Security",
    role: "Supervisor",
    email: "paul.d@email.com",
    phoneNumber: "07087654321",
    address: "5 Port Harcourt Way",
    city: "Garden City",
    state: "Rivers",
    country: "Nigeria",
    postalCode: "500101",
    zone: "South_Zone",
    location: "Port Harcourt",
  },
  {
    id: "#123459",
    firstName: "Simon",
    lastName: "Yahaya",
    department: "Logistics",
    role: "Driver",
    email: "simon.y@email.com",
    phoneNumber: "09012345678",
    address: "22 Kano Road",
    city: "Kaduna South",
    state: "Kaduna",
    country: "Nigeria",
    postalCode: "800101",
    zone: "North_Zone",
    location: "Kaduna",
  },
  {
    id: "#123460",
    firstName: "Grace",
    lastName: "Okafor",
    department: "Customer Success",
    role: "Lead",
    email: "grace.o@email.com",
    phoneNumber: "08123456789",
    address: "8 Enugu Close",
    city: "Enugu North",
    state: "Enugu",
    country: "Nigeria",
    postalCode: "400101",
    zone: "East_Zone",
    location: "Enugu",
  },
];
