import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import { ToastProvider } from "@/shared/ui/toast";
import { Sidebar } from "@/shared/ui/Sidebar/Sidebar";

const jakarta = Plus_Jakarta_Sans({
  variable: "--font-jakarta",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${jakarta.variable} antialiased`}>
        <Providers>
          <ToastProvider>
            <main>{children}</main>
            {/* <Sidebar />
            <main className="ml-[100px] flex-1">{children}</main> */}
          </ToastProvider>
        </Providers>
      </body>
    </html>
  );
}
