import { Department, Location, User } from "./types";

export const users: User[] = [
  {
    id: "1",
    firstName: "John",
    lastName: "Doe",
    department: "Engineering",
    location: "New York",
    email: "[EMAIL_ADDRESS]",
    phone: "123-456-7890",
    address: "123 Main St",
    country: "USA",
    state: "NY",
    city: "New York",
    postalCode: "10001",
    zone: "Zone 1",
    role: "USER",
    businessRole: "DEVICE_MANAGER",
    associatedDevices: [
      {
        id: "1",
        model: "iPhone 13 Pro Max",
        possesor: {
          name: "John Doe",
          email: "[EMAIL_ADDRESS]",
        },
        imei: "123456789012345",
        serialNumber: "123456789012345",
        macAddress: "12:34:56:78:90:12",
        lastSynced: "2022-01-01T12:00:00",
      },
    ],
  },
  {
    id: "2",
    firstName: "Jane",
    lastName: "Doe",
    department: "Engineering",
    location: "New York",
    email: "[EMAIL_ADDRESS]",
    phone: "123-456-7890",
    address: "123 Main St",
    country: "USA",
    state: "NY",
    city: "New York",
    postalCode: "10001",
    zone: "Zone 1",
    associatedDevices: [],
    role: "USER",
    businessRole: "DEVICE_MANAGER",
  },
  {
    id: "3",
    firstName: "Bob",
    lastName: "Smith",
    department: "Engineering",
    location: "New York",
    email: "[EMAIL_ADDRESS]",
    phone: "123-456-7890",
    address: "123 Main St",
    country: "USA",
    state: "NY",
    city: "New York",
    postalCode: "10001",
    zone: "Zone 1",
    associatedDevices: [],
    role: "USER",
    businessRole: "DEVICE_MANAGER",
  },
  {
    id: "4",
    firstName: "Alice",
    lastName: "Johnson",
    department: "Engineering",
    location: "New York",
    email: "[EMAIL_ADDRESS]",
    phone: "123-456-7890",
    address: "123 Main St",
    country: "USA",
    state: "NY",
    city: "New York",
    postalCode: "10001",
    zone: "Zone 1",
    associatedDevices: [],
    role: "USER",
    businessRole: "DEVICE_MANAGER",
  },
  {
    id: "5",
    firstName: "Charlie",
    lastName: "Brown",
    department: "Engineering",
    location: "New York",
    email: "[EMAIL_ADDRESS]",
    phone: "123-456-7890",
    address: "123 Main St",
    country: "USA",
    state: "NY",
    city: "New York",
    postalCode: "10001",
    zone: "Zone 1",
    associatedDevices: [],
    role: "USER",
    businessRole: "DEVICE_MANAGER",
  },
];

export const departments: Department[] = [
  {
    id: "1",
    name: "Engineering",
    description: "Engineering department",
    totalUsers: 10,
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "2",
    name: "Sales",
    description: "Sales department",
    totalUsers: 20,
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "3",
    name: "Marketing",
    description: "Marketing department",
    totalUsers: 30,
    createdAt: new Date("2024-01-01"),
  },
];

export const locations: Location[] = [
  {
    id: "1",
    name: "New York",
    description: "New York location",
    totalUsers: 10,
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "2",
    name: "Los Angeles",
    description: "Los Angeles location",
    totalUsers: 20,
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "3",
    name: "Chicago",
    description: "Chicago location",
    totalUsers: 30,
    createdAt: new Date("2024-01-01"),
  },
];
