import { DeviceAsset } from "./types";

export const MOCK_ASSETS: DeviceAsset[] = [
  {
    id: "1",
    name: "Samsung Galaxy S24 Ultra",
    assetId: "#234556677",
    possessorName: "Adewale Johnson",
    possessorEmail: "adewale.johnson@yahoo.com",
    type: "Mobile phone",
    imei: "Mobile phone",
    serialNumber: "PF3BCMEO",
    macAddress: "88:a4:c2:1a:83:fa",
    lastSynced: "22 Jan 2022 at 3:30",
  },
  {
    id: "2",
    name: "Google Pixel 8 Pro",
    assetId: "#234556677",
    possessorName: "Adewale Johnson",
    possessorEmail: "adewale.johnson@yahoo.com",
    type: "Mobile phone",
    imei: "Mobile phone",
    serialNumber: "PF3BCMEO",
    macAddress: "88:a4:c2:1a:83:fa",
    lastSynced: "22 Jan 2022 at 3:30",
  },
  {
    id: "3",
    name: "Xiaomi Pad 6",
    assetId: "#234556677",
    possessorName: "Unassigned",
    possessorEmail: "",
    type: "Tablet",
    imei: "Tablet",
    serialNumber: "PF3BCMEO",
    macAddress: "88:a4:c2:1a:83:fa",
    lastSynced: "22 Jan 2022 at 3:30",
    isUnassigned: true,
  },
  {
    id: "4",
    name: "Lenovo Tab P11 Gen 2",
    assetId: "#234556677",
    possessorName: "Adewale Johnson",
    possessorEmail: "adewale.johnson@yahoo.com",
    type: "Tablet",
    imei: "Tablet",
    serialNumber: "PF3BCMEO",
    macAddress: "88:a4:c2:1a:83:fa",
    lastSynced: "22 Jan 2022 at 3:30",
  },
  {
    id: "5",
    name: "Motorola Edge 50 Pro",
    assetId: "#234556677",
    possessorName: "Adewale Johnson",
    possessorEmail: "adewale.johnson@yahoo.com",
    type: "Mobile phone",
    imei: "Mobile phone",
    serialNumber: "PF3BCMEO",
    macAddress: "88:a4:c2:1a:83:fa",
    lastSynced: "22 Jan 2022 at 3:30",
  },
  {
    id: "6",
    name: "Realme 12 Pro+",
    assetId: "#234556677",
    possessorName: "Adewale Johnson",
    possessorEmail: "adewale.johnson@yahoo.com",
    type: "Mobile phone",
    imei: "Mobile phone",
    serialNumber: "PF3BCMEO",
    macAddress: "88:a4:c2:1a:83:fa",
    lastSynced: "22 Jan 2022 at 3:30",
  },
  {
    id: "7",
    name: "Samsung Galaxy Tab S9 FE",
    assetId: "#234556677",
    possessorName: "Adewale Johnson",
    possessorEmail: "adewale.johnson@yahoo.com",
    type: "Tablet",
    imei: "Tablet",
    serialNumber: "PF3BCMEO",
    macAddress: "88:a4:c2:1a:83:fa",
    lastSynced: "22 Jan 2022 at 3:30",
  },
];

export const MOCK_DAMAGED: DeviceAsset[] = MOCK_ASSETS.map((a, i) => ({
  ...a,
  id: `d-${i}`,
  dateReturned: "22 Jan 2022 at 3:30",
}));
